name: Provision Linux VM using reusable workflow.

on: [push]

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/provision-vm.yml
    with:
      ec2-image-id: ami-00cc4df80270a8821
      ec2-instance-type: t2.micro
      security-group-id: sg-0a3e6b53e86d0e69d
      subnet-id: subnet-06113672589e7e836
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

  run-commands: 
    needs: call-reusable-workflow
    runs-on: ${{ needs.call-reusable-workflow.outputs.instance_label }}
    steps:
      - name: Running script on linux
        run: |
          echo "Running from linux"
          cat /etc/os-release
          echo ${{ needs.call-reusable-workflow.outputs.instance_label }}
          

  remove-ec2-runner:
    needs: [call-reusable-workflow,run-commands]
    uses: ./.github/workflows/remove-vm.yml
    with: 
      ec2-instance-id: ${{ needs.call-reusable-workflow.outputs.ec2-instance-id }}
      ec2-runner-label: ${{ needs.call-reusable-workflow.outputs.instance_label }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}


  