name: Delete EC2 VM

on:
  workflow_call:
    inputs:
      ec2-instance-id:
        description: 'The instance ID for the EC2 instance'
        required: true
        type: string
      ec2-runner-label:
        description: 'The instance ID for the EC2 instance'
        required: true
        type: string
      aws-region:
        description: 'AWS Region'
        required: false
        type: string
        default: us-east-1
    secrets:
      aws-access-key-id:
        description: 'AWS Access Key ID'
        required: true
      aws-secret-access-key:
        description: 'AWS Secret Access Key'
        required: true
      github-token:
        description: 'Personal Access Token For GH'
        required: true

jobs:
  delete-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      # Configure AWS credentials using the aws-actions/configure-aws-credentials action
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}  # Specify your preferred region
      
      - name: Output EC2 Instance ID
        run: |
          echo "EC2 Instance"
          echo ${{ inputs.ec2-instance-id }}
          echo ${{ inputs.ec2-runner-label }}

      # Start the EC2 GitHub runner
      - name: Terminate EC2 GitHub runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.github-token }}
          ec2-instance-id: ${{ inputs.ec2-instance-id }}        
          label: ${{ inputs.ec2-runner-label }}

      - name: Output EC2 Instance ID
        run: |
          echo "EC2 Instance Deleted"
          