name: Run on Windows EC2

on: [push]

jobs:
  ec2-github-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      # Configure AWS credentials using the aws-actions/configure-aws-credentials action
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Specify your preferred region

      # Start the EC2 GitHub runner
      - name: Start EC2 GitHub runner
        id: ec2
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          ec2-instance-type: t2.micro          
          ec2-image-id: ami-00cc4df80270a8821
          subnet-id: subnet-06113672589e7e836
          security-group-id: sg-0a3e6b53e86d0e69d
          aws-key-pair-name: aws-vm-login-key
          

      # Run a script on the Windows instance
      - name: Run a script on Windows
        run: |
          echo "Running on EC2 instance"
          whoami
          cat /etc/os-release

      # Terminate the EC2 instance
      - name: Terminate the EC2 instance
        if: always()
        run: |
          aws ec2 terminate-instances --instance-ids ${{ steps.ec2.outputs.ec2-instance-id }} \
            --region us-east-1